services:
  - docker

before_install:
  - docker build -t chandanjainn/docker-multi-images -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true chandanjainn/docker-multi-images npm test

after_success:
  - docker build -t chandanjainn/multi-client ./client
  - docker build -t chandanjainn/multi-nginx ./nginx
  - docker build -t chandanjainn/multi-backend ./backend
  - docker build -t chandanjainn/multi-worker ./worker

  # Log in to docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin

  # Push these images to docker hub
  - docker push chandanjainn/multi-client
  - docker push chandanjainn/multi-nginx
  - docker push chandanjainn/multi-backend
  - docker push chandanjainn/multi-worker
